export const textInputBackground = '#5E6A75'
export const textInputBorder = '#D33A39'
export const textBorderFocused = '#0f62fc'
export const textInputBackground2 = '#D33A39'
export const inputTextColor = '#FFFFFF'

export const contentBackgroundColor = '#122332'

export const borderDarkRed = '#D33A39'
export const boderLightBrown = '#FAF3F4'

export const textColor = '#393A4A'
export const textColorSecondary = '#6B6C7E'
export const red = '#9A0002'
export const veryDarkBlue = '#22215B'
export const veryLightBlue = '#F0F5FF'
export const borderGrey = '#E7E7ED'
export const veryLightRed = '#FEEFEF'
export const veryLightGreen = '#E2EFEA'
export const veryLightYellow = '#FFF3DB'
export const veryLightGrey = '#E7E7ED'
export const green = '#287D3C'
export const yellow = '#FFB321'
export const borderDarkGrey = '#CDCED9'
export const white = '#ffffff'
